name: endlessh
adopt-info: endlessh
summary: Endlessh is an SSH tarpit that very slowly sends an endless, random SSH banner
descripton: |
  
  Endlessh is an SSH tarpit that very slowly sends an endless, random SSH banner. 
  It keeps SSH clients locked up for hours or even days at a time. The purpose is 
  to put your real SSH server on another port and then let the script kiddies get 
  stuck in this tarpit instead of bothering a real server.

  Since the tarpit is in the banner before any cryptographic exchange occurs, this 
  program doesn't depend on any cryptographic libraries. It's a simple, single-threaded, 
  standalone C program. It uses poll() to trap multiple clients at a time.
  
  Usage: endlessh [-vhs] [-d MS] [-f CONFIG] [-l LEN] [-m LIMIT] [-p PORT]
  -4        Bind to IPv4 only
  -6        Bind to IPv6 only
  -d INT    Message millisecond delay [10000]
  -f        Set and load config file [/etc/endlessh/config]
  -h        Print this help message and exit
  -l INT    Maximum banner line length (3-255) [32]
  -m INT    Maximum number of clients [4096]
  -p INT    Listening port [2222]
  -s        Print diagnostics to syslog instead of standard output
  -v        Print diagnostics (repeatable)
  
grade: stable
confinement: strict

base: core18
grade: stable
confinement: strict
compression: lzo

apps:
  endlessh:
  command: endlessh
  plugs:
    - network-bind
    - network

parts:
  endlessh:
    plugin: autotools
    source: https://github.com/skeeto/endlessh
    source-type: git
    build-packages:
      - gcc
      
    override-pull: |
      snapcraftctl pull
      git checkout `git describe --tags --abbrev=0`      
